### ISSUE TITLE
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session

### ISSUE THREAD

**Issue by Cristal84** [King-of-Spades/AppCenter-Test-Samples#15]
I'm trying to test the iOS app with Appium on AppCenter but I have a problem. In Appium latest versions Searching by name was deprecated. How can I solve this problem?

**Comment by King-of-Spades** [comment]
Currently the AppCenter team is working on updating our support for Appium latest versions, but it's not available yet. When that support is updated it will be documented here: https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium
