### ISSUE TITLE
[Appium (Android)] Readme requires a few more details on set up steps. 

### ISSUE THREAD

**Issue by King-of-Spades** [King-of-Spades/AppCenter-Test-Samples#6]
- How to install Appium: 
> sudo npm install -g appium 
(may require additional permission arguments to work. One of our engineers had to use the workaround noted here: https://github.com/npm/npm/issues/17268)
- setting the jdk path in the integration-test.iml 
- setting the ANDROID_HOME path per: https://stackoverflow.com/questions/28296237/set-android-home-environment-variable-in-mac
- setting the path to the sample APK:
https://github.com/King-of-Spades/AppCenter-Test-Samples/blob/master/Appium/Android/Maven/src/test/java/com/microsoft/altframeworktraining/StartAppTest.java#L33

https://github.com/King-of-Spades/AppCenter-Test-Samples/blob/e5205966d432c37b89b38f124a31978b7fd08e0b/Appium/Android/Maven/src/test/java/com/microsoft/altframeworktraining/StartAppTest.java#L33

To actually upload, Maven also needs to be installed, so that it can package the upload:
- https://maven.apache.org/install.html

**Comment by King-of-Spades** [comment]
I also need to make an equivalent modification for iOS, but that's not ready yet.

**Comment by King-of-Spades** [comment]
Hmm...looks like maybe Maven which is used for the upload has to be installed separately: https://maven.apache.org/install.html. Asking @ahanag22 what her results are with this additional step included.

**Comment by ahanag22** [comment]
Yes that issue has been fixed. I have downloaded and installed Apache Maven and then added the bin directory of the created directory apache-maven-3.5.3 to the PATH environment variable. Now I can run the command "mvn -DskipTests -P prepare-for-upload package"

**Comment by King-of-Spades** [comment]
I ended up bundling this with #8, because of information crossover.
